2023-11-17 14:28:09 | INFO | model_worker | Loading the model ['Baichuan2-13B'] on worker 581dccb9 ...
2023-11-17 14:28:14 | INFO | model_worker | Register to controller
2023-11-17 14:28:14 | ERROR | stderr | Process model_worker - Baichuan2-13B:
2023-11-17 14:28:14 | ERROR | stderr | Traceback (most recent call last):
2023-11-17 14:28:14 | ERROR | stderr |   File "/home/pc/anaconda3/envs/law_chat/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2023-11-17 14:28:14 | ERROR | stderr |     self.run()
2023-11-17 14:28:14 | ERROR | stderr |   File "/home/pc/anaconda3/envs/law_chat/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-11-17 14:28:14 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-11-17 14:28:14 | ERROR | stderr |   File "/home/pc/PycharmProjects/chat0.2.4/startup.py", line 303, in run_model_worker
2023-11-17 14:28:14 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2023-11-17 14:28:14 | ERROR | stderr |   File "/home/pc/PycharmProjects/chat0.2.4/startup.py", line 135, in create_model_worker_app
2023-11-17 14:28:14 | ERROR | stderr |     worker = ModelWorker(
2023-11-17 14:28:14 | ERROR | stderr |   File "/home/pc/anaconda3/envs/law_chat/lib/python3.10/site-packages/fastchat/serve/model_worker.py", line 96, in __init__
2023-11-17 14:28:14 | ERROR | stderr |     self.init_heart_beat()
2023-11-17 14:28:14 | ERROR | stderr |   File "/home/pc/PycharmProjects/chat0.2.4/startup.py", line 117, in _new_init_heart_beat
2023-11-17 14:28:14 | ERROR | stderr |     target=fastchat.serve.model_worker.heart_beat_worker, args=(self,), daemon=True,
2023-11-17 14:28:14 | ERROR | stderr | AttributeError: module 'fastchat.serve.model_worker' has no attribute 'heart_beat_worker'
