2023-11-24 10:27:14 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb6298ece80>, 'Connection to 192.168.1.104 timed out. (connect timeout=5)'))
2023-11-24 10:27:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb76e53c460>: Failed to establish a new connection: [Errno 113] No route to host'))
2023-11-24 10:27:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb76e53d1e0>: Failed to establish a new connection: [Errno 113] No route to host'))
