2023-10-21 02:58:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3b1c7f03d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-10-21 02:58:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3b1c7f33d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-10-21 02:58:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3b1c7f3c70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-10-21 02:58:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3b1c8ac550>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-10-21 02:59:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3b1c7f3730>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-10-21 02:59:08 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3b1c7f3310>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
