2023-10-21 02:58:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd4cc57b9a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-10-21 02:58:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd4cc5c8850>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-10-21 02:58:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd4cc5c90f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-10-21 02:58:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd4cc57b9d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-10-21 02:58:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd4cc5c8fd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-10-21 02:59:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd4cc5c8760>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-10-21 02:59:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd4cc5c9990>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-10-21 02:59:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd4cc5ca230>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
