2023-12-14 13:37:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf5e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:37:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbee90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:37:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd780>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:37:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf5b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:38:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:38:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf520>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:38:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd2a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:38:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f265c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:38:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f26350>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:38:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbefb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:38:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbffd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:38:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd120>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:38:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf550>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:38:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f24dc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:38:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe0e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:38:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbdde0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbda50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbdea0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbcd00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f25ed0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbcdc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc3a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbfee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf2b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f25540>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd870>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbcb80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbfe80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbeb00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbdf30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f24340>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbdd50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbfc40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbdd80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f27220>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd720>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe980>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc9a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe500>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe9b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f27b50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe020>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf7f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe1a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbfb50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f26320>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbcb80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd750>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf820>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc910>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd360>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f27e50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf520>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd240>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f27b20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc160>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbfca0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbcaf0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbca60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe140>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f25000>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe2c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f25840>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbdc30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf5b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbfe80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbeb00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbdf30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f24d00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf940>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbfeb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbca30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbef80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe3b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f26ec0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf7c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe7d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd3f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc3d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f26b30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc0d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf910>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbda20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbdae0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbed40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f25e10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe3b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbcdf0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbffa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe830>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbead0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f25720>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd3f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe7d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf7c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc430>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f275b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbdc30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf730>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe230>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd5a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc370>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f26aa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc760>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf460>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc7c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:47:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbebc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:47:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd120>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:47:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f275b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:47:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf2e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:47:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbce80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:47:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf8e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:47:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbcee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:48:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe200>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:48:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd480>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:48:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbde70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:48:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe0e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:48:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f254e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:48:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd6c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:48:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc7c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:48:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf460>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe020>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f27580>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb15df367a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbcee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbfeb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbca30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbef80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f27af0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f254b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe140>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe3e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe710>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc8e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f26200>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc580>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbdd50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf940>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbec20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe980>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f25660>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf700>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc9a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe500>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe4d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f26c20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f27d30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbfe80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf5b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd000>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf580>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f25270>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbfd30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbef80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbca30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbfeb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbcaf0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f26500>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbcdc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbfc40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbdd80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f26ec0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f26b30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc9a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe500>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe4d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd600>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f266e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe2c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc2e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbfe20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb15df354b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f24a60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd420>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf640>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbfc70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe200>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd5a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f25420>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbfeb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd750>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe980>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb15df37070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbfb50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf040>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbeef0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd990>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f244c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb15df36440>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd390>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf160>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe140>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbead0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f24730>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd3f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbfb80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc2e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbce80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbfee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f25f00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbcd60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbedd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe320>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbfa30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f266e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbcb80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbcf40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe740>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd630>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f26ce0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe4d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe110>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc3d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbfb20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f24580>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbcd00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc910>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf2e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f270a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f26740>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf970>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe500>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbffd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbeb60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f24a90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe5f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbdea0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbdd80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe4a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc280>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f268c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f254b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f25cf0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbdcf0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbfd30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe9b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd0c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f26080>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f25ba0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc160>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:28 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd540>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbca30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf5b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe740>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f24520>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f25d80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb15df35360>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:08 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f24ee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f274c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbfb50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbeda0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:28 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd060>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb15df356f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbfe80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd720>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f25e40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f25d80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc760>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:08 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbffa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd300>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe500>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f24a60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:28 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f275b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe5f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd300>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbffa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f268c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f25ae0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf7f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:08 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc970>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbdab0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f25ba0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f26290>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:28 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf940>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbeda0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf160>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbdae0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f25840>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f25fc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbcaf0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf160>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:08 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbeda0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd660>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f26470>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f27d90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:28 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe4a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc2e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe6e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f27b80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f24820>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbea70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd4b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:08 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe4d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f270d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb15df36c20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f267d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:28 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f252a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe080>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc910>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe140>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbec20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe9e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc790>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f24e80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:08 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f270d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb15df365f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f253c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f24eb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:28 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbfdc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbef80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbffa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb15df37ca0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf640>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd360>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f27220>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f254e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:08 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb15df35840>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf0a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe8f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbdae0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:28 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbda80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f26920>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f27010>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd1b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc9d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd990>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc280>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f27340>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:08 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f25630>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbfee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf2e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:28 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f27c10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f264d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf5b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbdd50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd750>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbfac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f266e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f27c70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:08 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbdab0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd750>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbdd50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe710>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:28 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f25c00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f27460>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe680>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd7e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf730>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f26500>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f26cb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbeef0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:08 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf7c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbfc10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f27430>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:28 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb15df35420>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f27220>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f26380>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf460>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbea70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd4b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf220>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:08 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbdae0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f251e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f27430>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb15df34430>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:28 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f24850>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f270a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbde70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbd2a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe7a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb15df365f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbcca0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc970>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:08 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbe710>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f270a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f258a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb15df37dc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:28 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f25d80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc8b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbcd00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb15df35030>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc2b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbf850>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:12:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:12:08 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbc5e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:12:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f26050>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:12:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb166f258a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:12:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb172bbfee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
