2023-11-24 10:27:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e7fef85e0>: Failed to establish a new connection: [Errno 113] No route to host'))
2023-11-24 10:27:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e7fef8f70>: Failed to establish a new connection: [Errno 113] No route to host'))
2023-11-24 10:27:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e7fef9810>: Failed to establish a new connection: [Errno 113] No route to host'))
2023-11-24 10:27:24 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e7feabdf0>: Failed to establish a new connection: [Errno 113] No route to host'))
2023-11-24 10:27:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e7fef9270>: Failed to establish a new connection: [Errno 113] No route to host'))
